version: "3.7"
services:
  app:
    env_file:
      - ./.env
      - ./shared/network_config
    build:
      context: ./app/vendor/laravel/sail/runtimes/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    container_name: app
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 0
    volumes:
      - './app:/var/www/html'
      - './shared:/shared'
    networks:
      - app_network
    restart: always
    depends_on:
      - database

  app_init:
    env_file:
      - ./.env
    build:
      context: ./app_init
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    container_name: app_init
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 0
    volumes:
      - './app:/var/www/html'
      - './app_init/wait-for-it.sh:/usr/local/bin/wait-for-it.sh'
      - './app_init/app_init.sh:/usr/local/bin/app_init.sh'
      - './app_init/db_init.sh:/usr/local/bin/db_init.sh'
    networks:
      - app_network
    depends_on:
      - database
      - app
    entrypoint: /usr/local/bin/app_init.sh
      
  database:
    env_file:
      - ./.env
    image: 'mysql:8.0'
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_APP_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_APP_DATABASE}'
      MYSQL_USER: '${DB_APP_USERNAME}'
      MYSQL_PASSWORD: '${DB_APP_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './database/storage:/var/lib/mysql'
    networks:
      - app_network
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - app_network
    restart: always
    ports:
      - 8080:8080
    restart: always

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    volumes:
      - ./proxy/config:/etc/nginx
      - ./proxy/cert:/etc/ssl/certs
      - ./proxy/key:/etc/ssl/private
    environment:
      - SUBJECT_ALTERNATE_NAME=pcm.lcl
      - TEST=test
    restart: always
networks:
  app_network:
