#!/bin/bash

### Set working directory
cd /home/pcmuser/pcm_selfhosted

### Generate passwords
export MYSQL_RANDOM_PW=$(< /dev/urandom tr -dc A-Z-a-z-0-9 | head -c${1:-32};echo;)
export MYSQL_RANDOM_ROOT_PW=$(< /dev/urandom tr -dc A-Z-a-z-0-9 | head -c${1:-32};echo;)
export ARTISAN_KEY=$(php ./app/artisan key:generate --show)

### Store secrets
sed -i "s\^DB_APP_PASSWORD=$\DB_APP_PASSWORD=$MYSQL_RANDOM_PW\g" ./.env
sed -i "s\^DB_APP_ROOT_PASSWORD=$\DB_APP_ROOT_PASSWORD=$MYSQL_RANDOM_ROOT_PW\g" ./.env
sed -i "s\^APP_KEY=$\APP_KEY=$ARTISAN_KEY\g" ./.env

### Run initial setup
if [ -f ./initial ]; then

        ### Generate SSL certificate
        openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=US/ST=Washington/L=Auburn/O=PCM/CN=patchcablemgr.com" -addext "subjectAltName = DNS:patchcablemgr.com" -keyout ./proxy/key/key.pem  -out ./proxy/cert/cert.pem

        ### Set permissions
        sudo chown :pcmuser ./proxy/cert/cert.pem
        sudo chown :pcmuser ./proxy/key/key.pem
        sudo chmod g+rw ./proxy/cert/cert.pem
        sudo chmod g+rw ./proxy/key/key.pem

        ### Upgrade to latest code
        ./watch_app_update

        ### Remove initial file
        rm ./initial
else

        ### Start application
        sudo /home/pcmuser/pcm_selfhosted/app/vendor/bin/sail -f /home/pcmuser/pcm_selfhosted/docker-compose.yml up -d --build
fi
