---
- name: Configure server
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:

  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present

  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes

  - name: Apt Update
    ansible.builtin.apt:
      update_cache: yes

  - name: Apt Upgrade
    ansible.builtin.apt:
      upgrade: yes

  - name: GET Nodejs repo installer
    ansible.builtin.get_url:
      url: https://deb.nodesource.com/setup_16.x
      dest: ./nodesource_setup.sh
      mode: '0770'

  - name: Install Nodejs repo
    shell: bash ./nodesource_setup.sh

  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
        - nodejs
        - php8.1-xml
        - php8.1-curl
        - php8.1-common
        - php8.1-cli
        - ca-certificates
        - curl
        - gnupg

  - name: Install Docker
    ansible.builtin.apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present

  - name: Get current username
    set_fact:
      current_username: "{{ lookup('env', 'USER') }}"
    become: no

  - name: Add {{current_username}} to docker group
    ansible.builtin.user:
      name: "{{ current_username }}"
      groups: docker
      append: yes

  # - name: Update apt packages
  #   remote_user: ubuntu
  #   apt:
  #     update_cache: yes

  # - name: Install docker
  #   remote_user: ubuntu
  #   apt:
  #     name: docker-ce
  #     state: present
  #     update_cache: yes
  #   #notify: Start docker on boot

  # - name: Add remote "ubuntu" user to "docker" group
  #   remote_user: ubuntu
  #   user:
  #     name: "ubuntu"
  #     group: "docker"
  #     append: yes

  # - name: Install docker-compose
  #   remote_user: ubuntu
  #   get_url: 
  #     url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
  #     dest: /usr/local/bin/docker-compose
  #     mode: 'u+x,g+x'

  - name: Install composer2
    shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php && php -r "unlink('composer-setup.php');"

  - name: Move composer2 to bin
    shell: mv composer.phar /usr/local/bin/composer

  - name: Clear app directory (part 1)
    ansible.builtin.file:
      path: app
      state: absent

  - name: Clear app directory (part 2)
    ansible.builtin.file:
      path: app
      state: directory
    become: no

  - name: Clone pcm_code repository
    git:
      repo: https://github.com/patchcablemgr/pcm_code.git
      dest: app
      accept_hostkey: yes
    become: no

  - name: Install php modules (app)
    shell: cd app && composer install
    become: no

  - name: Generate App key
    shell: php app/artisan key:generate --show
    register: ArtisanAppKey

  - name: Compile secrets
    set_fact:
      secret_vars:
        app_key: "{{ArtisanAppKey.stdout}}"
        db_appuser_pw: "{{ lookup('ansible.builtin.password', '/dev/null', seed=lookup('community.general.random_string', length=12), length=12, chars=['ascii_letters', 'digits']) }}"
        db_pcmuser_pw: "{{ lookup('ansible.builtin.password', '/dev/null', seed=lookup('community.general.random_string', length=12), length=12, chars=['ascii_letters', 'digits']) }}"
        db_root_pw: "{{ lookup('ansible.builtin.password', '/dev/null', seed=lookup('community.general.random_string', length=12), length=12, chars=['ascii_letters', 'digits']) }}"

  - name: Store secrets
    copy:
      content: "{{ secret_vars | to_json }}"
      dest: "secret_vars.json"

  - name: Read secrets
    set_fact:
      secret_vars_from_file: "{{ lookup('file', 'secret_vars.json') | from_json }}"

  - name: Print variable
    ansible.builtin.debug:
      var: secret_vars_from_file

  - name: Template dot.env.j2 file to .env
    ansible.builtin.template:
      src: files/dot.env.j2
      dest: .env
      owner: root
      group: root
      mode: 0664

  - name: Set permissions ./pcm_selfhosted/app/bootstrap/cache
    ansible.builtin.file:
      path: app/bootstrap/cache
      mode: 'o+rw'
      recurse: yes

  - name: Set permissions ./pcm_selfhosted/app/storage
    ansible.builtin.file:
      path: app/storage
      owner: root
      group: root
      mode: 'g+rw'
      recurse: yes

  - name: Install node packages (app/app)
    shell: cd app && npm install
    become: no

  - name: Install node packages (app/frontend)
    shell: cd app/frontend && npm install
    become: no

  - name: Compile (app)
    shell: npm run --prefix app prod
    become: no

  - name: Generate self-signed cert & key
    shell: openssl req -nodes -new -x509 -keyout {{playbook_dir}}/proxy/key/key.pem -out {{playbook_dir}}/proxy/cert/cert.pem -sha256 -days 365 -subj "/C=US/ST=Washington/CN=patchcablemgr.com"
    become: no

  - name: Set cron reboot job
    ansible.builtin.cron:
      name: "Start PCM"
      special_time: reboot
      job: "/home/pcmuser/pcm_selfhosted/pcmStart"
    become: no

  - name: Template patchcablemgr.service file to /lib/systemd/system/patchcablemgr.service
    ansible.builtin.template:
      src: files/patchcablemgr.service.j2
      dest: /lib/systemd/system/patchcablemgr.service
      owner: root
      group: root
      mode: 0644

  - name: Enable and start patchcablemgr
    ansible.builtin.systemd:
      name: patchcablemgr
      daemon_reload: true
      enabled: true
      state: restarted