#!/bin/bash

source /home/pcmuser/pcm_selfhosted/shared/network_config

#
# Creates a backup
cp /etc/netplan/00-installer-config.yaml /etc/netplan/00-installer-config.yaml.bk_`date +%Y%m%d%H%M`

if [ $DHCP = 'yes' ]
then
cat > /etc/netplan/00-installer-config.yaml <<EOF
network:
  ethernets:
    ens160:
      dhcp4: yes
  version: 2
EOF
else
cat > /etc/netplan/00-installer-config.yaml <<EOF
network:
  ethernets:
    ens160:
      dhcp4: no
      addresses:
      - $HOST
      gateway4: $GATEWAY
      nameservers:
        addresses:
        - $DNS
  version: 2
EOF
fi
sudo netplan apply
