#!/bin/bash

sudo git -C /home/pcmuser/pcm_selfhosted/ pull
sudo /home/pcmuser/pcm_selfhosted/laravel/vendor/bin/sail -f /home/pcmuser/pcm_selfhosted/docker-compose.yml up --build
sudo php /home/pcmuser/pcm_selfhosted/laravel/vendor/bin/envoy run --path=/home/pcmuser/pcm_selfhosted/laravel/Envoy.blade.php deploy
