#!/bin/bash

source /home/garrett/pcm_infra/shared/ssl_config

echo $CERT > ~/watch_ssl_config_test
echo $KEY >> ~/watch_ssl_config_test
echo $(pwd) >> ~/watch_ssl_config_test
if [ -f "/home/garrett/pcm_infra/shared/certs/$CERT" ] && [ -f "/home/garrett/pcm_infra/shared/keys/$KEY" ]; then
	#echo "here1" >> ~/watch_ssl_config_test
	cp /home/garrett/pcm_infra/shared/certs/$CERT /home/garrett/pcm_infra/nginx/cert/cert.pem 2>~/watch_error
	cp /home/garrett/pcm_infra/shared/keys/$KEY /home/garrett/pcm_infra/nginx/key/key.pem

	sudo docker exec nginx nginx -s reload
fi
