#!/bin/bash

### Pull latest code
git -C /home/pcmuser/pcm_selfhosted/ pull
git -C /home/pcmuser/pcm_selfhosted/app/ pull

### Start containers
sudo /home/pcmuser/pcm_selfhosted/app/vendor/bin/sail -f /home/pcmuser/pcm_selfhosted/docker-compose.yml up -d --build

### Install
cd /home/pcmuser/pcm_selfhosted/app
composer install
npm install
cd /home/pcmuser/pcm_selfhosted/app/frontend
npm install

### Compile
cd /home/pcmuser/pcm_selfhosted/app
npm run prod

### Migrations
cd /home/pcmuser/pcm_selfhosted
sudo ./app/vendor/bin/sail artisan migrate --path=database/migrations/tenant

### Seeder
cd /home/pcmuser/pcm_selfhosted
sudo ./app/vendor/bin/sail artisan db:seed
