#!/bin/bash

source /home/pcmuser/pcm_selfhosted/shared/ssl_config

if [ -f "/home/pcmuser/pcm_selfhosted/shared/certs/$CERT" ] && [ -f "/home/pcmuser/pcm_selfhosted/shared/keys/$KEY" ]; then
	
	cp /home/pcmuser/pcm_selfhosted/shared/certs/$CERT /home/pcmuser/pcm_selfhosted/proxy/cert/cert.pem
	cp /home/pcmuser/pcm_selfhosted/shared/keys/$KEY /home/pcmuser/pcm_selfhosted/proxy/key/key.pem

	sudo docker exec proxy nginx -s reload
fi
